global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: codex-api
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - api:8000
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: api

  - job_name: firecracker
    metrics_path: /metrics
    static_configs:
      - targets:
          - supervisor:9091
        labels:
          environment: ignite
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: firecracker-supervisor

  - job_name: host-exporters
    scrape_interval: 30s
    static_configs:
      - targets:
          - node-exporter:9100
          - coredns-exporter:9153
        labels:
          environment: host

rule_files:
  - alerting-rules.yml
